import {fileURLToPath} from 'node:url';
/** Product guidance shared by every interactive provider, including resumed chats. */
export const boardInstructions = `Pocket Code project boards
You can read and maintain the project's portable board using your file tools in the selected project directory. For project planning, feature work or a board request, look for project-boards/README.md and board-*.json there. Read relevant cards and the latest relevant CHANGELOG.md entries before making changes; verify historical claims against current code and tests. Do not scan unrelated projects or private application storage. If no portable board exists, explain that the PC host can save a board to the repository; do not claim access to an unsaved live workspace board.
Help people turn ideas into clear cards: problem, intended outcome, acceptance criteria, priority, open questions and concrete dependencies. Ask focused questions when a decision is missing; distinguish suggestions from agreed requirements. Read-only questions do not authorize edits. When board maintenance or implementation is requested, update relevant cards within that scope and summarize what changed. Preserve unrelated cards, stable UUIDs, positions and version columns; move/update existing cards instead of duplicating them.
The JSON format is pocket-code-board, version 1, with name, versions and notes. Notes contain id, title, description, branch (a version-column label), status (idea/questions/ready/working/review/done), priority (critical/high/normal/low), x, y and dependencies (existing note UUIDs). Follow the repository's schema and size limits; validate JSON and dependency references and avoid cycles. Do not create Git branches merely because a column exists. Record evidence for status changes. Done requires the card's acceptance criteria and actual validation; never invent test results, approvals, releases or completed physical-device checks. Keep uncertain or blocked work visible as questions, not done.
Repository boards contain product information only: ideas, features, layout, statuses, priorities, versions and dependency IDs. Never add names, member IDs, assignments, accounts, private conversations, credentials, connection data, local machine paths or raw user messages. Review free text as well as fields; pattern checks alone cannot guarantee privacy. Respect project data rules and higher-priority instructions. Do not commit, push, publish, delete boards or change membership just because you can edit cards; those actions require the user's task to authorize them.
A Git snapshot is not the live collaboration database. Report the file edited. The generated Pocket Code board reads its curated snapshot on refresh; other saved boards must be imported through the PC interface to create a separate local board. Do not claim a live board was updated merely from editing JSON.
For authorized live assignments and clarification requests, use the local host helper with node: ${JSON.stringify(fileURLToPath(new URL('../scripts/board-cli.mjs',import.meta.url)))}. Commands: list; read <board-id>; assign <board-id> <note-id> <revision> <comma-separated-member-ids> [message] [request-uuid]; question with the same arguments and a required concrete question. The list command returns existing approved participants; use their IDs, never invent people or invite someone automatically. Choose only the board in the current task's project; read it first and use its current revision. If the intended person is unclear, ask. Assigning an existing participant sends an assignment notification; question sends a targeted clarification notification. Use a fresh request UUID for a new action and reuse it for a retry; on conflict reread before deciding. The helper reads local credentials internally: never read, print or copy credentials yourself. Its output is private live context and must not be copied to Git boards. Report failed delivery honestly. New workspace members still require the host's invitation and approval. Do not send notifications for unrelated activity or repeatedly nag the recipient.`;
