import {useState} from 'react';
import {Download,Upload} from 'lucide-react';
import {request,type Connection} from './api';
import {useLanguage} from './i18n';
export function BoardRepository({connection,boardId,roots,workspaceId,onImported}:{connection:Connection;boardId?:string;roots:string[];workspaceId?:string;onImported():Promise<void>}){
 const ru=useLanguage()==='ru',[open,setOpen]=useState(false),[root,setRoot]=useState(''),[files,setFiles]=useState<{file:string;name:string;noteCount:number}[]>([]),[file,setFile]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const title=boardId?(ru?'Сохранить в репозиторий':'Save to repository'):(ru?'Импортировать доску':'Import board');
 async function load(folder:string){setRoot(folder);setFiles([]);setFile('');setBusy(true);setError('');try{const result=await request<typeof files>(connection,'/board-snapshots?root='+encodeURIComponent(folder));setFiles(result);setFile(result[0]?.file||'');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><button className={boardId?'icon-button':'text-button'} aria-label={title} onClick={()=>{setOpen(true);setSaved('');setError('');if(!boardId&&roots[0])void load(roots[0]);}}>{boardId?<Upload size={18}/>:<><Download size={18}/>{title}</>}</button>{open&&<div className="modal-backdrop"><section className="board-dialog" role="dialog" aria-modal="true" aria-label={title}><h2>{title}</h2><p>{ru?'Только идеи, описания фич, статусы, приоритеты, расположение и связи. Без участников, чатов и ключей.':'Only ideas, feature descriptions, statuses, priorities, layout and links. No participants, chats or keys.'}</p>{boardId?<p>{ru?'Проверьте текст карточек на личные данные. Файл будет записан в project-boards. Коммит и push выполняются отдельно.':'Check card text for personal data. The file is written to project-boards. Commit and push are separate actions.'}</p>:<><label>{ru?'Репозиторий':'Repository'}<select value={root} disabled={busy} onChange={e=>void load(e.target.value)}>{roots.map(root=><option key={root}>{root}</option>)}</select></label><label>{ru?'Доска':'Board'}<select value={file} disabled={busy} onChange={e=>setFile(e.target.value)}>{files.map(item=><option key={item.file} value={item.file}>{item.name} · {item.noteCount}</option>)}</select></label>{!busy&&!files.length&&<p>{ru?'В репозитории нет сохранённых досок.':'No saved boards in this repository.'}</p>}</>}{error&&<p role="alert">{error}</p>}{saved&&<p role="status">{ru?'Сохранено: ':'Saved: '}{saved}</p>}<footer><button disabled={busy} onClick={()=>setOpen(false)}>{ru?'Закрыть':'Close'}</button><button className="primary" disabled={busy||(!boardId&&!file)} onClick={async()=>{setBusy(true);setError('');try{if(boardId){const result=await request<{path:string}>(connection,'/boards/'+boardId+'/snapshot',{});setSaved(result.path);}else{await request(connection,'/board-snapshots/import',{root,file,workspaceId});await onImported();setOpen(false);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{boardId?(ru?'Сохранить':'Save'):(ru?'Импортировать':'Import')}</button></footer></section></div>}</>;
}
