import {useEffect,useState} from 'react';
import {request,type Connection} from './api';
import {getLanguage} from './i18n';
export function CopilotConnection({connection}:{connection:Connection|null}){
 const ru=getLanguage()==='ru',[state,setState]=useState('checking'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!connection)return;let active=true;void request<{authenticated:boolean;error?:string}>(connection,'/copilot/status').then(value=>{if(active){setState(value.authenticated?'connected':'idle');setError(value.error||'');}}).catch(()=>{if(active){setState('idle');setError(ru?'Нет связи с Copilot на ПК':'Cannot reach Copilot on the PC');}});return()=>{active=false;};},[connection]);
 useEffect(()=>{if(!connection||state!=='waiting'&&state!=='checking')return;let active=true;const timer=setInterval(()=>void request<{state:string;error:string}>(connection,'/copilot/login').then(value=>{if(active&&value.state!=='idle'){setState(value.state);setError(value.error);if(value.state==='connected')window.dispatchEvent(new Event('pocket-code-providers'));}}).catch(()=>{}),2000);return()=>{active=false;clearInterval(timer);};},[connection,state]);
 async function login(){if(!connection)return;setBusy(true);setError('');try{const value=await request<{state:string;error:string}>(connection,'/copilot/login',{});setState(value.state);setError(value.error);window.dispatchEvent(new Event('pocket-code-providers'));}catch(error){setError((error as Error).message);}finally{setBusy(false);}}
 return <section><h3>GitHub Copilot</h3><p role="status">{state==='connected'?(ru?'Подключён через GitHub на ПК':'Connected through GitHub on your PC'):state==='waiting'?(ru?'Завершите вход GitHub в браузере на ПК':'Complete GitHub sign-in in the browser on your PC'):state==='checking'?(ru?'Проверяем существующий вход…':'Checking existing sign-in…'):(ru?'Вход на ПК определяется автоматически':'Existing PC sign-in is detected automatically')}</p>{error&&<p className="error" role="alert">{error}</p>}<button className="secondary" disabled={!connection||busy||state==='waiting'||state==='checking'} onClick={()=>void login()}>{state==='connected'?(ru?'Проверить подключение':'Check connection'):(ru?'Подключить GitHub Copilot':'Connect GitHub Copilot')}</button><p className="muted">{ru?'Разрешения на команды и изменения файлов запрашиваются в чате.':'Command and file permissions are requested in the chat.'}</p></section>;
}
