import {useState} from 'react';
import QRCode from 'qrcode';
import {Plus,ChevronDown,ScanLine} from 'lucide-react';
import {request,type Connection} from './api';
import {useLanguage} from './i18n';
import {connectionKind} from './connection-kind';
import {PersonAvatar} from './NoteAssignees';
import {WorkspaceMembers} from './WorkspaceMembers';
import type {useProjectWorkspaces} from './project-workspaces';
import './desktop-workspaces.css';

export function DesktopWorkspaces({connection,value,roots,addresses,onBoard}:{connection:Connection;value:ReturnType<typeof useProjectWorkspaces>;roots:string[];addresses:{url:string}[];onBoard():void}){
  const ru=useLanguage()==='ru',l=(en:string,other:string)=>ru?other:en;
  const [expanded,setExpanded]=useState(''),[create,setCreate]=useState(false),[title,setTitle]=useState(''),[password,setPassword]=useState(''),[root,setRoot]=useState(''),[role,setRole]=useState('host'),[address,setAddress]=useState(0),[qr,setQr]=useState<{id:string;token:string;image:string;url:string;role:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const selectedAddress=addresses[Math.min(address,addresses.length-1)]?.url;
  async function invite(id:string){if(!selectedAddress||busy)return;setBusy(true);setQr(null);setError('');try{const result=await request<{token:string}>(connection,'/workspaces/'+id+'/invitation',{role});setQr({id,token:result.token,url:selectedAddress,role,image:await QRCode.toDataURL(JSON.stringify({type:'pocket-workspace',version:1,url:selectedAddress,token:result.token,workspaceId:id}),{margin:2,width:280})});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="desktop-settings workspace-manager"><header><h1>WorkSpace</h1><button className="primary" disabled={!value.catalog.canManageWorkspaces} onClick={()=>{setCreate(true);setRoot(roots[0]||'');}}><Plus size={18}/>{l('Create workspace','Создать рабочую область')}</button></header>
    <p role="alert">{error||value.error}</p>
    {value.catalog.workspaces.map(ws=><details key={ws.id} open={expanded===ws.id} onToggle={e=>{if(e.currentTarget.open)setExpanded(ws.id);}}><summary onClick={e=>{e.preventDefault();setExpanded(expanded===ws.id?'':ws.id);setQr(null);}}><span><strong>{ws.name}</strong><small>{ws.people?.length||0} {l('participants','участников')}</small></span><ChevronDown size={18}/></summary><div className="workspace-foldout"><button onClick={()=>{value.select(ws.id);onBoard();}}>{l('Open board','Открыть доску')}</button><ul className="workspace-roster">{ws.people?.map(person=><li key={person.id}><PersonAvatar person={person}/><span>{person.name}<small>{person.role}</small></span></li>)}</ul>{value.catalog.canManageWorkspaces&&<details className="workspace-options"><summary>{l('Manage participants','Управление участниками')}</summary><WorkspaceMembers workspace={ws} connection={connection} onChange={value.refresh}/></details>}
      <details className="workspace-options"><summary>{l('Invite by QR','Пригласить по QR')}</summary><section className="workspace-invitation"><h2>{l('Join this workspace','Присоединение к этой рабочей области')}</h2><p className="muted">{l('This QR opens the shared board. PC Connection uses a separate QR.','Этот QR открывает общую доску. Для подключения к ПК используется отдельный QR.')}</p><label>{l('Connection method','Способ подключения')}<select value={address} onChange={e=>{setAddress(Number(e.target.value));setQr(null);}}>{addresses.map((item,i)=><option key={item.url} value={i}>{connectionKind(item.url)} · {item.url}</option>)}</select></label><label>{l('Participant role','Роль участника')}<select value={role} onChange={e=>{setRole(e.target.value);setQr(null);}}>{['host','developer','reviewer','qa','viewer'].map(r=><option key={r}>{r}</option>)}</select></label><button disabled={busy||!selectedAddress} onClick={()=>void invite(ws.id)}><ScanLine size={18}/>{l('Generate joining QR','Создать QR для входа')}</button>{qr?.id===ws.id&&<figure><img src={qr.image} alt={l('Private workspace invitation','Личное приглашение в рабочую область')}/><figcaption>{ws.name} · {connectionKind(qr.url)} · {qr.role}</figcaption></figure>}</section></details>
    </div></details>)}
    {create&&<div className="modal-backdrop"><form className="board-dialog" role="dialog" aria-modal="true" aria-label={l('Create workspace','Создать рабочую область')} onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=await request<{id:string}>(connection,'/workspaces',{name:title,password,roots:[root]});value.select(result.id);await value.refresh();setExpanded(result.id);setCreate(false);setTitle('');setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h2>{l('Create workspace','Создать рабочую область')}</h2><label>{l('Name','Название')}<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{l('Repository','Репозиторий')}<select required value={root} onChange={e=>setRoot(e.target.value)}>{roots.map(r=><option key={r} value={r}>{r}</option>)}</select></label><label>{l('Password','Пароль')}<input type="password" required minLength={10} maxLength={256} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><p role="alert">{error}</p><footer><button type="button" onClick={()=>setCreate(false)}>{l('Cancel','Отмена')}</button><button className="primary" disabled={busy||!root}>{l('Create','Создать')}</button></footer></form></div>}
  </section>;
}
