import {useEffect,useState} from 'react';
import {Smartphone,Monitor,RefreshCw} from 'lucide-react';
import {request,type Connection} from './api';
import {desktopCall} from './desktop-bridge';
import {startVisiblePoll} from './visible-poll';
import {useLanguage} from './i18n';
type Device={id:string;name:string;platform:string;version:string;model?:string;pairedAt:number;lastSeen:number;status:'online'|'offline'};
export function DesktopDevices({connection,online}:{connection:Connection;online:boolean}){
 const ru=useLanguage()==='ru',l=(en:string,r:string)=>ru?r:en;
 const [devices,setDevices]=useState<Device[]>([]),[error,setError]=useState(''),[revision,setRevision]=useState(0),[pending,setPending]=useState(''),[confirm,setConfirm]=useState<Device|null>(null),[editing,setEditing]=useState<Device|null>(null),[name,setName]=useState('');
 useEffect(()=>{if(!online)return;let active=true;const stop=startVisiblePoll(async()=>{try{const data=await request<Device[]>(connection,'/devices');if(!Array.isArray(data))throw Error(l('Update the PC host to manage devices.','Обновите сервер ПК для управления устройствами.'));if(active){setDevices(data);setError('');}}catch(e){if(active)setError((e as Error).message);}},3000);return()=>{active=false;stop();};},[connection,online,revision]);
 async function act(device:Device,action:'device-disconnect'|'device-rename'){setPending(device.id);setError('');try{await desktopCall(action,{deviceId:device.id,...(action==='device-rename'?{name:name.trim()}:{})});setConfirm(null);setEditing(null);setRevision(n=>n+1);}catch(e){setError((e as Error).message);}finally{setPending('');}}
 return <section className="desktop-devices"><header><h2>{l('Connected devices','Подключённые устройства')}</h2><button className="icon-button" aria-label={l('Refresh devices','Обновить устройства')} disabled={!online||!!pending} onClick={()=>setRevision(n=>n+1)}><RefreshCw size={18}/></button></header>
 <p className="muted">{l('Devices go offline after 45 seconds without contact. Each phone appears once, even after scanning again. Disconnect removes the device and revokes its access; running AI tasks continue on the PC.','Без связи более 45 секунд устройство считается не в сети. Каждый телефон отображается один раз, даже после повторного сканирования. Отключение удаляет устройство и отзывает доступ; запущенные задачи AI продолжаются на ПК.')}</p>
 {error&&<p role="alert" className="error">{error}</p>}{!online&&<p role="status">{l('Connect the PC host to manage devices.','Подключите сервер ПК для управления устройствами.')}</p>}
 {!devices.length&&!error&&online&&<p>{l('No paired devices yet. Scan the QR above on your phone.','Устройств пока нет. Отсканируйте QR выше на телефоне.')}</p>}
 <ul>{devices.map(device=><li key={device.id}>{device.platform==='android'?<Smartphone size={22}/>:<Monitor size={22}/>}<div><strong>{device.name}</strong><span className={'desktop-device-status '+(online?device.status:'offline')}>{!online?l('Status unavailable','Статус недоступен'):device.status==='online'?l('Online','В сети'):l('Offline','Не в сети')}</span><small>{[device.model&&device.model!==device.name?device.model:'',device.platform==='android'?'Android':l('Browser','Браузер'),device.version].filter(Boolean).join(' · ')} · {l('Last seen','Последняя связь')}: {new Date(device.lastSeen).toLocaleString(ru?'ru':'en')}</small>
 {editing?.id===device.id?<div className="device-edit"><input aria-label={l('Device name','Имя устройства')} maxLength={80} value={name} onChange={e=>setName(e.target.value)}/><button className="text-button" disabled={!name.trim()||!!pending} onClick={()=>void act(device,'device-rename')}>{l('Save','Сохранить')}</button><button className="text-button" onClick={()=>setEditing(null)}>{l('Cancel','Отмена')}</button></div>:<div className="device-actions"><button className="text-button" disabled={!online||!!pending} onClick={()=>{setEditing(device);setName(device.name);setConfirm(null);}}>{l('Rename','Переименовать')}</button>{<button className="text-button danger" disabled={!online||!!pending} onClick={()=>{setConfirm(device);setEditing(null);}}>{l('Disconnect','Отключить')}</button>}</div>}
 {confirm?.id===device.id&&<div role="alert"><p>{l('This device will need to scan the new QR to reconnect.','Для повторного подключения устройство должно отсканировать новый QR.')}</p><button className="secondary danger" disabled={!!pending} onClick={()=>void act(device,'device-disconnect')}>{l('Disconnect device','Отключить устройство')}</button><button className="text-button" disabled={!!pending} onClick={()=>setConfirm(null)}>{l('Cancel','Отмена')}</button></div>}</div></li>)}</ul></section>;
}
