import React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from './App';
import './styles.css';
import '@fontsource/golos-text/400.css';
import '@fontsource/golos-text/500.css';
import '@fontsource/golos-text/600.css';
import '@fontsource/manrope/500.css';
import '@fontsource/manrope/700.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
