import {useEffect,useState} from 'react';
import {request,type Connection} from './api';
import {useLanguage} from './i18n';
import type {ProjectWorkspace} from '../server/boards';
export function PairingRole({connection,workspaces,onChange}:{connection:Connection;workspaces:ProjectWorkspace[];onChange(role:string,workspaceId?:string):Promise<void>}){
 const ru=useLanguage()==='ru',l=(en:string,r:string)=>ru?r:en;
 const [role,setRole]=useState('host'),[workspaceId,setWorkspace]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[ready,setReady]=useState(false);
 useEffect(()=>{let live=true;void request<{role:string;workspaceId?:string}>(connection,'/pairing-role').then(v=>{if(live){setRole(v.role||'host');setWorkspace(v.workspaceId||'');setReady(true);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[connection]);
 async function change(next:string,workspace=workspaceId){if(next!=='host'&&!workspace)return;setBusy(true);setError('');try{await onChange(next,workspace||undefined);setRole(next);setWorkspace(workspace);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="pairing-role"><label>{l('Role for this QR','Роль пользователя по QR')}<select aria-label={l('QR role','Роль по QR')} disabled={!ready||busy} value={role} onChange={e=>void change(e.target.value,workspaceId||workspaces.at(-1)?.id)}><option value="host">Host</option><option value="viewer" disabled={!workspaces.length}>{l('Viewer','Наблюдатель')}</option><option value="developer" disabled={!workspaces.length}>{l('Developer','Разработчик')}</option><option value="reviewer" disabled={!workspaces.length}>{l('Reviewer','Ревьюер')}</option><option value="qa" disabled={!workspaces.length}>QA</option></select></label>{!!workspaces.length&&<p className="qr-workspace-name">{workspaces.find(w=>w.id===(workspaceId||workspaces.at(-1)?.id))?.name}</p>}<small>{l('Host is the default for testing. Each role change replaces the QR.','Host выбран по умолчанию для тестов. При смене роли QR заменяется.')}</small>{role!=='host'&&!workspaceId&&<p role="alert">{l('Create a workspace first. The current QR still grants Host access.','Сначала создайте область. Текущий QR пока даёт доступ Host.')}</p>}{error&&<p role="alert">{error}</p>}</section>;
}
