import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {X,GitBranch,RefreshCw} from 'lucide-react';
import {request,type Connection} from './api';
import {useLanguage} from './i18n';
import {useModal} from './navigation';
import {Review} from './Review';
import {taskStageLabel,type TaskRun} from './task-run-ui';
import type {TaskCheck} from '../server/task-checks';
import type {BoardNoticeTarget} from './BoardNotifications';
import './task-runs.css';
type Result={run:TaskRun;verificationCurrent:boolean;approvalCurrent:boolean};
export function TaskRunPanel({connection,initial,onClose,onChat,onBoard}:{connection:Connection;initial:TaskRun;onClose():void;onChat?(run:TaskRun):void;onBoard?(target:BoardNoticeTarget):void}){
  const ru=useLanguage()==='ru',l=(en:string,other:string)=>ru?other:en;
  const [result,setResult]=useState<Result>({run:initial,verificationCurrent:false,approvalCurrent:false});
  const run=result.run,[checks,setChecks]=useState<TaskCheck[]>(initial.verificationPlan||[]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[review,setReview]=useState(false);
  const [custom,setCustom]=useState(false),[executable,setExecutable]=useState(''),[args,setArgs]=useState('[]');
  const panel=useRef<HTMLElement|null>(null),dirty=useRef(false),mounted=useRef(true),requesting=useRef(false),generation=useRef(0),mutating=useRef(false);
  useModal(panel,true,()=>{if(review)setReview(false);else onClose();});
  async function load(){if(requesting.current||mutating.current)return;requesting.current=true;const at=++generation.current;try{const data=await request<Result>(connection,'/task-runs/'+initial.id+'/result');if(mounted.current&&at===generation.current){setResult(previous=>data.run.revision>=previous.run.revision?data:previous);if(!dirty.current)setChecks(data.run.verificationPlan||[]);}}catch(e){if(mounted.current&&at===generation.current)setError((e as Error).message);}finally{if(at===generation.current)requesting.current=false;}}
  useEffect(()=>{mounted.current=true;void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},2000);return()=>{mounted.current=false;generation.current++;clearInterval(timer);};},[initial.id,connection.url,connection.token]);
  async function mutate(action:string,data:Record<string,unknown>={}){if(mutating.current)return;mutating.current=true;generation.current++;requesting.current=false;setBusy(true);setError('');try{const next=await request<TaskRun>(connection,`/task-runs/${run.id}/${action}`,{revision:run.revision,...data});if(!mounted.current)return;setResult({run:next,approvalCurrent:false,verificationCurrent:false});if(action==='checks'){dirty.current=false;setChecks(next.verificationPlan||[]);}}catch(e){if(mounted.current)setError((e as Error).message);}finally{mutating.current=false;if(mounted.current){setBusy(false);await load();}}}
  const running=run.jobs.at(-1)?.status==='running',checking=run.verification?.status==='running',locked=busy||running||checking;
  const edit=(next:TaskCheck[])=>{dirty.current=true;setChecks(next);};
  async function presets(){setError('');try{const data=await request<{checks:TaskCheck[]}>(connection,`/task-runs/${run.id}/checks`);if(mounted.current){edit(data.checks);if(!data.checks.length)setError(l('No package scripts found. Add a verification command below.','Скрипты проверки не найдены. Добавьте команду ниже.'));}}catch(e){if(mounted.current)setError((e as Error).message);}}
  function add(){try{const values=JSON.parse(args);if(!Array.isArray(values)||values.some(v=>typeof v!=='string'))throw Error();if(!executable.trim()||checks.length>=8)throw Error();edit([...checks,{label:executable.trim().split(/[\\/]/).at(-1)!,executable:executable.trim(),args:values,timeoutMs:120000}]);setExecutable('');setArgs('[]');setCustom(false);setError('');}catch{setError(l('Enter a program and a JSON array of string arguments.','Укажите программу и JSON-массив строковых аргументов.'));}}
  async function source(){if(!onBoard)return;try{const value=await request<{board:BoardNoticeTarget['board'];noteId:string}>(connection,`/task-runs/${run.id}/board`);onBoard({...value,connection,message:'',requestId:Date.now()});onClose();}catch(e){setError((e as Error).message);}}
  return createPortal(<div className="task-run-backdrop"><section ref={panel} className="task-run-panel" role="dialog" aria-modal="true" aria-label={l('Task result','Результат задачи')}>
    <header><div><small>{l('Task result','Результат задачи')}</small><h2>{run.title}</h2></div><button type="button" className="icon-button" aria-label={l('Close task result','Закрыть результат задачи')} onClick={onClose}><X size={20}/></button></header>
    <div className="task-run-body"><p className="task-run-stage" role="status">{taskStageLabel(run.stage,ru)}{run.stage==='approved'&&!result.approvalCurrent?' · '+l('approval is no longer current','одобрение больше не актуально'):''}</p>
    {run.worktree&&<p className="task-run-branch"><GitBranch size={16}/><code>{run.worktree.branch}</code><small>{l('Base','Основа')}: {run.worktree.baseCommit.slice(0,10)}</small></p>}
    <div className="task-run-actions">{onChat&&run.worktree&&<button type="button" onClick={()=>onChat(run)}>{l('Open chat','Открыть чат')}</button>}{run.worktree&&<button type="button" onClick={()=>setReview(true)}>{l('Review task changes','Изменения задачи')}</button>}{onBoard&&<button type="button" onClick={()=>void source()}>{l('Source card','Исходная карточка')}</button>}<button type="button" className="icon-button" aria-label={l('Refresh task','Обновить задачу')} onClick={()=>void load()}><RefreshCw size={17}/></button></div>
    {run.noteSnapshot&&<details className="task-check-evidence"><summary>{l('Accepted task and criteria','Задача и критерии на момент запуска')}</summary><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{run.noteSnapshot.description||run.noteSnapshot.title}</p></details>}
    {run.error&&<p role="alert">{run.error}</p>}{error&&<p role="alert">{error}</p>}
    <section className="task-run-checks"><h3>{l('Verification commands','Команды проверки')}</h3><p className="muted">{l('Saved commands run automatically after the AI finishes. They execute in this task’s working copy. Passing commands does not replace review of the acceptance criteria.','Сохранённые команды запускаются автоматически после завершения AI в рабочей копии задачи. Успешные команды не заменяют проверку критериев готовности.')}</p>
      {checks.map((check,index)=><div className="task-check-plan" key={index}><code>{[check.executable,...check.args].join(' ')}</code><button type="button" className="icon-button" disabled={locked} aria-label={l('Remove check','Удалить проверку')+' '+check.label} onClick={()=>edit(checks.filter((_,i)=>i!==index))}><X size={16}/></button></div>)}
      {!checks.length&&<p>{l('No checks configured. Approval stays unavailable.','Проверки не настроены. Одобрение недоступно.')}</p>}
      <div className="task-run-actions"><button type="button" disabled={locked} onClick={()=>void presets()}>{l('Use project scripts','Взять скрипты проекта')}</button><button type="button" disabled={locked||checks.length>=8} onClick={()=>setCustom(v=>!v)}>{l('Add command','Добавить команду')}</button></div>
      {custom&&<div className="task-check-custom"><label>{l('Program (no shell)','Программа (без оболочки)')}<input value={executable} onChange={e=>setExecutable(e.target.value)} placeholder="node"/></label><label>{l('Arguments (JSON)','Аргументы (JSON)')}<input value={args} onChange={e=>setArgs(e.target.value)} placeholder={'["--test", "test.mjs"]'}/></label><button type="button" onClick={add}>{l('Add','Добавить')}</button></div>}
      <div className="task-run-actions"><button type="button" disabled={locked||run.stage==='approved'||!dirty.current} onClick={()=>void mutate('checks',{checks})}>{l('Save automatic checks','Сохранить автопроверки')}</button><button type="button" disabled={locked||run.stage==='working'||run.stage==='approved'||!checks.length} onClick={()=>void mutate('check',{checks})}>{checking?l('Checking…','Проверяется…'):l('Run checks now','Проверить сейчас')}</button></div>
    </section>
    {run.verification&&<section><h3>{l('Check results','Результаты проверок')}</h3><p>{run.verification.status}{!result.verificationCurrent&&run.verification.status!=='running'?' · '+l('working copy changed; recheck required','рабочая копия изменилась; нужна повторная проверка'):''}</p>{run.verification.error&&<p role="alert">{run.verification.error}</p>}{run.verification.evidence.map((check,i)=><details key={i} className="task-check-evidence"><summary>{check.passed?'✓':'×'} {check.label} · {check.exitCode??l('no exit code','нет кода выхода')}{check.timedOut?' · timeout':''}</summary><pre>{check.output||l('No output','Нет вывода')}</pre>{check.truncated&&<p>{l('Only the end of the output is shown.','Показан только конец вывода.')}</p>}</details>)}</section>}
    <section><h3>{l('Human approval','Одобрение человеком')}</h3><p className="muted">{l('Review the task diff, chat and acceptance criteria. Approval is tied to the checked file snapshot. New changes require new checks. It does not merge or publish.','Посмотрите диф задачи, чат и критерии готовности. Одобрение привязано к проверенному состоянию файлов. Новые изменения требуют повторных проверок. Слияние и публикация не выполняются.')}</p><button type="button" className="primary" disabled={locked||!result.verificationCurrent||run.stage!=='review'} onClick={()=>void mutate('approve')}>{l('Approve checked result','Одобрить проверенный результат')}</button>{run.stage==='approved'&&<button type="button" disabled={locked} onClick={()=>void mutate('resume')}>{l('Resume task','Продолжить задачу')}</button>}</section>
    </div>
    {review&&run.worktree&&<Review connection={connection} cwd={run.worktree.cwd} taskRunId={run.id} onClose={()=>setReview(false)}/>}
  </section></div>,document.body);
}
