import {WorkspaceMembers} from './WorkspaceMembers';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Plus,RefreshCw,MessageSquare,ZoomIn,ZoomOut,X} from 'lucide-react';
import {request,type Connection} from './api';
import {useLanguage} from './i18n';
import {ProjectWorkspacePicker,type useProjectWorkspaces} from './project-workspaces';
import type {ProjectBoard,BoardNote} from '../server/boards';
import './work-boards.css';
export type BoardChat={root:string;prompt:string;note:BoardNote;boardId:string};
type BoardView=ProjectBoard&{branches:string[];error?:string};
export function WorkBoards({connection,roots,workspaces,onChat}:{connection:Connection;roots:string[];workspaces:ReturnType<typeof useProjectWorkspaces>;onChat(chat:BoardChat):void}){
  const ru=useLanguage()==='ru',l=(en:string,ruText:string)=>ru?ruText:en;
  const [board,setBoard]=useState<BoardView|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<BoardNote|null>(null),[form,setForm]=useState<'workspace'|'board'|null>(null),[title,setTitle]=useState(''),[folders,setFolders]=useState<string[]>([]),[root,setRoot]=useState(''),[zoom,setZoom]=useState(1);
  const [password,setPassword]=useState(''),[editingWorkspace,setEditingWorkspace]=useState(false);
  const host=workspaces.catalog.host;const canEdit=host||!!workspaces.workspace&&workspaces.workspace.role!=='viewer';
  const lock=useRef(false),navigation=useRef(0),canvas=useRef<HTMLDivElement>(null);
  useEffect(()=>{navigation.current++;setBoard(null);setEditing(null);setForm(null);},[workspaces.selected]);
  async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
  async function open(id:string){const epoch=++navigation.current;await run(async()=>{const next=await request<BoardView>(connection,'/boards/'+id);if(epoch===navigation.current){setBoard(next);setEditing(null);setZoom(1);}});}
  async function save(notes:BoardNote[],versions=board!.versions){if(!board)return;const current=board;await run(async()=>{const next=await request<ProjectBoard>(connection,'/boards/'+current.id,{revision:current.revision,notes,versions});setBoard(old=>old?.id===next.id?{...old,...next}:old);setEditing(null);void workspaces.refresh();});}
  const newNote=()=>{if(!board)return;setEditing({id:crypto.randomUUID(),title:'',description:'',branch:'',status:'idea',owner:'',x:24,y:70+board.notes.filter(n=>!n.branch).length*190,dependencies:[]});};
  const versions=board?['',...new Set([...board.versions,...board.notes.map(n=>n.branch).filter(Boolean)])]:[];
  const statusLabels={idea:l('Idea','Идея'),questions:l('Questions','Уточнение'),ready:l('Ready','Готово к работе'),working:l('Working','В работе'),review:l('Review','Проверка'),done:l('Done','Готово')};
  function startChat(note:BoardNote){if(!board)return;const deps=note.dependencies.map(id=>board.notes.find(n=>n.id===id)).filter(Boolean);onChat({boardId:board.id,root:board.root,note,prompt:[l('Help develop this project idea. Ask clarifying questions first; identify acceptance criteria and dependencies. Do not implement until we agree on the plan.','Помоги проработать идею проекта. Сначала задай уточняющие вопросы, определи критерии готовности и зависимости. Не приступай к реализации, пока мы не согласуем план.'),note.title,note.description,note.branch?`Git branch: ${note.branch}`:'',deps.length?'Dependencies:\n'+deps.map(n=>n!.title+' ('+n!.status+')').join('\n'):''].filter(Boolean).join('\n\n')});}
  function drag(event:React.PointerEvent<HTMLButtonElement>,note:BoardNote){if(event.button!==0||busy||!canEdit)return;const el=event.currentTarget,card=el.closest('article')!;el.setPointerCapture(event.pointerId);const sx=event.clientX,sy=event.clientY;let x=note.x,y=note.y,moved=false;const move=(e:PointerEvent)=>{x=Math.max(0,Math.min(19500,note.x+(e.clientX-sx)/zoom));y=Math.max(60,Math.min(19500,note.y+(e.clientY-sy)/zoom));moved=Math.abs(e.clientX-sx)+Math.abs(e.clientY-sy)>4;card.style.left=x+'px';card.style.top=y+'px';};const end=(e:PointerEvent)=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',end);card.style.left=note.x+'px';card.style.top=note.y+'px';if(e.type==='pointerup'&&moved)void save(board!.notes.map(n=>n.id===note.id?{...n,x,y}:n));};el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);}
  return <section className="work-boards">
    <header className="board-toolbar">{board?<><button className="icon-button" aria-label={l('Back to boards','К доскам')} onClick={()=>{navigation.current++;setBoard(null);}}><ArrowLeft/></button><h2>{board.name}</h2><button className="icon-button" disabled={busy} aria-label={l('Refresh board','Обновить доску')} onClick={()=>void open(board.id)}><RefreshCw size={18}/></button></>:<><h2>{l('Work','В работе')}</h2><ProjectWorkspacePicker value={workspaces}/>{host&&<button onClick={()=>{setPassword('');setEditingWorkspace(false);setTitle('');setFolders([]);setForm('workspace');}}><Plus size={16}/>{l('Workspace','Рабочая область')}</button>}</>}</header>
    {(error||workspaces.error)&&<div role="alert" className="board-error">{error||workspaces.error}</div>}
    {!board?<div className="board-index">{workspaces.workspace?<><div className="board-toolbar"><h3>{workspaces.workspace.name}</h3>{host&&<><button onClick={()=>{setTitle('');setRoot(workspaces.workspace!.roots[0]||'');setForm('board');}}><Plus size={16}/>{l('Project board','Доска проекта')}</button><button onClick={()=>{setPassword('');setEditingWorkspace(true);setFolders(workspaces.workspace!.roots);setTitle(workspaces.workspace!.name);setForm('workspace');}}>{l('Edit workspace','Изменить область')}</button></>}</div><WorkspaceMembers workspace={workspaces.workspace} connection={connection} onChange={workspaces.refresh}/><p className="muted">{l('Project boards and chats share this workspace.','Проектные доски и чаты объединены этой рабочей областью.')}</p>{workspaces.catalog.boards.filter(b=>b.workspaceId===workspaces.selected).map(b=><button className="board-index-item" key={b.id} onClick={()=>void open(b.id)}><strong>{b.name}</strong><span>{b.root.split(/[\\/]/).at(-1)} · {b.noteCount} {l('notes','заметок')}</span></button>)}{!workspaces.catalog.boards.some(b=>b.workspaceId===workspaces.selected)&&<p>{l('Create the first board for a project in this workspace.','Создайте первую доску для проекта в этой области.')}</p>}</>:<p>{l('Create or select a workspace, then add project boards. Its projects also filter your chats.','Создайте или выберите рабочую область, затем добавьте проектные доски. Её проекты также определяют список чатов.')}</p>}</div>:<>
      <div className="board-tools"><button disabled={busy||!canEdit} onClick={newNote}><Plus size={16}/>{l('Note','Заметка')}</button><label>{l('Version / Git branch','Версия / ветка Git')}<select aria-label={l('Add version','Добавить версию')} value="" disabled={busy||!canEdit} onChange={e=>{if(e.target.value)void save(board.notes,[...board.versions,e.target.value]);}}><option value="">{l('Add branch…','Добавить ветку…')}</option>{board.branches.filter(b=>!versions.includes(b)).map(b=><option key={b}>{b}</option>)}</select></label><button className="icon-button" aria-label={l('Zoom out','Отдалить')} onClick={()=>setZoom(z=>Math.max(.25,z-.15))}><ZoomOut size={18}/></button><button onClick={()=>setZoom(1)}>{Math.round(zoom*100)}%</button><button className="icon-button" aria-label={l('Zoom in','Приблизить')} onClick={()=>setZoom(z=>Math.min(1.75,z+.15))}><ZoomIn size={18}/></button><span role="status">{busy?l('Saving…','Сохранение…'):l('Saved on PC','Сохранено на ПК')}</span></div>
      {board.error&&<p className="board-git-warning">{board.error}</p>}
      <div className="board-viewport" ref={canvas}><div style={{width:Math.max(1100,versions.length*340,...board.notes.map(n=>n.x+330))*zoom,height:Math.max(800,...board.notes.map(n=>n.y+240))*zoom}}><div className="board-canvas" style={{width:Math.max(1100,versions.length*340,...board.notes.map(n=>n.x+330)),height:Math.max(800,...board.notes.map(n=>n.y+240)),transform:`scale(${zoom})`}}>
        {versions.map((v,i)=><div className="board-version" key={v} style={{left:i*340}}><strong>{v||l('Ideas','Идеи')}</strong></div>)}
        <svg className="board-edges" aria-label={l('Dependencies','Зависимости')}>{board.notes.flatMap(n=>n.dependencies.map(id=>{const dep=board.notes.find(v=>v.id===id);return dep?<g key={n.id+id}><path d={`M ${dep.x+280} ${dep.y+80} C ${dep.x+340} ${dep.y+80},${n.x-60} ${n.y+80},${n.x} ${n.y+80}`}/><circle cx={n.x} cy={n.y+80} r="4"/></g>:null;}))}</svg>
        {board.notes.map(n=><article className={'board-note status-'+n.status} key={n.id} style={{left:n.x,top:n.y}}><button className="note-drag" aria-label={l('Move note','Переместить заметку')+' '+n.title} onPointerDown={e=>drag(e,n)} onKeyDown={e=>{const dir:Record<string,[number,number]>={ArrowLeft:[-24,0],ArrowRight:[24,0],ArrowUp:[0,-24],ArrowDown:[0,24]};if(canEdit&&dir[e.key]){e.preventDefault();const [x,y]=dir[e.key];void save(board.notes.map(v=>v.id===n.id?{...v,x:Math.max(0,v.x+x),y:Math.max(60,v.y+y)}:v));}}}>⠿ <span>{statusLabels[n.status]}</span></button><button className="note-content" onClick={()=>setEditing({...n,dependencies:[...n.dependencies]})}><strong>{n.title}</strong><p>{n.description||l('Add details…','Добавить описание…')}</p><small>{n.branch||l('No version yet','Без версии')}{n.owner?' · '+n.owner:''}</small></button><button className="note-chat" disabled={!host&&!n.chat} onClick={()=>startChat(n)}><MessageSquare size={15}/>{n.chat?l('Open chat','Открыть чат'):l('Discuss with AI','Обсудить с AI')}</button></article>)}
      </div></div></div></>}
    {form&&<div className="modal-backdrop"><form className="board-dialog" role="dialog" aria-modal="true" aria-label={form==='workspace'?l('Workspace settings','Рабочая область'):l('New board','Новая доска')} onSubmit={e=>{e.preventDefault();void run(async()=>{if(form==='workspace'){const result=await request<{id:string}>(connection,'/workspaces',{...(editingWorkspace?{id:workspaces.workspace!.id}:{}),name:title,roots:folders,...(password?{password}:{})});workspaces.select(result.id);}else{const result=await request<ProjectBoard>(connection,'/boards',{workspaceId:workspaces.selected,name:title,root});setBoard(await request<BoardView>(connection,'/boards/'+result.id));}await workspaces.refresh();setForm(null);});}}><h2>{form==='workspace'?l('Workspace','Рабочая область'):l('Project board','Доска проекта')}</h2><label>{l('Name','Название')}<input autoFocus required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label>{form==='workspace'?<><label>{l('Workspace password (10+ characters)','\u041f\u0430\u0440\u043e\u043b\u044c \u043e\u0431\u043b\u0430\u0441\u0442\u0438 (10+)')}<input type="password" autoComplete="new-password" required={!editingWorkspace} minLength={10} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label><fieldset><legend>{l('Projects','Проекты')}</legend>{roots.map(p=><label className="board-check" key={p}><input type="checkbox" checked={folders.includes(p)} onChange={e=>setFolders(e.target.checked?[...folders,p]:folders.filter(v=>v!==p))}/><span>{p.split(/[\\/]/).at(-1)}<small>{p}</small></span></label>)}</fieldset></>:<label>{l('Project','Проект')}<select value={root} onChange={e=>setRoot(e.target.value)}>{workspaces.workspace?.roots.map(p=><option key={p} value={p}>{p.split(/[\\/]/).at(-1)}</option>)}</select></label>}<p role="alert">{error}</p><footer><button type="button" onClick={()=>setForm(null)}>{l('Cancel','Отмена')}</button><button className="primary" disabled={busy||!title.trim()||form==='workspace'&&!folders.length}>{l('Save','Сохранить')}</button></footer></form></div>}
    {editing&&board&&<div className="modal-backdrop"><form className="board-dialog" role="dialog" aria-modal="true" aria-label={l('Note details','Параметры заметки')} onSubmit={e=>{e.preventDefault();void save([...board.notes.filter(n=>n.id!==editing.id),editing]);}}><h2>{l('Note','Заметка')}</h2><label>{l('Title','Название')}<input autoFocus required maxLength={160} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>{l('Description / acceptance criteria','Описание / критерии готовности')}<textarea maxLength={20000} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>{l('Version / branch','Версия / ветка')}<select value={editing.branch} onChange={e=>{const branch=e.target.value,index=versions.indexOf(branch);setEditing({...editing,branch,x:Math.max(0,index)*340+24});}}><option value="">{l('Ideas','Идеи')}</option>{[...new Set([...board.branches,...versions])].filter(Boolean).map(v=><option key={v}>{v}</option>)}</select></label><label>{l('Status','Статус')}<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as BoardNote['status']})}>{Object.entries(statusLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>{l('Owner / role','Исполнитель / роль')}<input maxLength={120} value={editing.owner} onChange={e=>setEditing({...editing,owner:e.target.value})}/></label><fieldset><legend>{l('Depends on','Зависит от')}</legend>{board.notes.filter(n=>n.id!==editing.id).map(n=><label className="board-check" key={n.id}><input type="checkbox" checked={editing.dependencies.includes(n.id)} onChange={e=>setEditing({...editing,dependencies:e.target.checked?[...editing.dependencies,n.id]:editing.dependencies.filter(id=>id!==n.id)})}/>{n.title}</label>)}</fieldset><p role="alert">{error}</p><footer><button type="button" onClick={()=>setEditing(null)}>{l('Cancel','Отмена')}</button><button className="primary" disabled={busy||!canEdit||!editing.title.trim()}>{l('Save','Сохранить')}</button></footer></form></div>}
  </section>;
}
