import {BoardPeople,BoardTaskMeta,boardPeople,priorityLabels} from './BoardPeople';
import {BoardBranchHeading} from './BoardBranchHeading';
import {BoardContextMenu} from './BoardContextMenu';
import {useBoardZoom} from './use-board-zoom';
import {WorkspaceParticipants} from './WorkspaceParticipants';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Plus,RefreshCw,MessageSquare,X} from 'lucide-react';
import {request,type Connection} from './api';
import {useLanguage} from './i18n';
import {ProjectWorkspacePicker,type useProjectWorkspaces} from './project-workspaces';
import type {ProjectBoard,BoardNote} from '../server/boards';
import './work-boards.css';
export type BoardChat={root:string;prompt:string;note:BoardNote;boardId:string};
type BoardView=ProjectBoard&{branches:string[];error?:string};
export function WorkBoards({connection,roots,workspaces,onChat}:{connection:Connection;roots:string[];workspaces:ReturnType<typeof useProjectWorkspaces>;onChat(chat:BoardChat):void}){
  const ru=useLanguage()==='ru',l=(en:string,ruText:string)=>ru?ruText:en;
  const [board,setBoard]=useState<BoardView|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<BoardNote|null>(null),[form,setForm]=useState<'workspace'|'board'|null>(null),[title,setTitle]=useState(''),[folders,setFolders]=useState<string[]>([]),[root,setRoot]=useState(''),[zoom,setZoom]=useState(1);
  const [view,setView]=useState<'board'|'people'>('board');
  const [branchAction,setBranchAction]=useState<{previous?:string;name:string}|null>(null);
  const [password,setPassword]=useState(''),[editingWorkspace,setEditingWorkspace]=useState(false);
  const host=workspaces.catalog.host;const manageWorkspace=host&&!!connection.desktop&&workspaces.catalog.canManageWorkspaces===true;const canEdit=host||!!workspaces.workspace&&workspaces.workspace.role!=='viewer';
  const lock=useRef(false),navigation=useRef(0),canvas=useRef<HTMLDivElement>(null);
  useEffect(()=>{try{setView(localStorage.getItem('pocket-board-view:'+board?.id)==='people'?'people':'board');}catch{setView('board');}},[board?.id]);
  const people=boardPeople(workspaces.workspace,board?.notes||[]);
  function changeView(next:'board'|'people'){setView(next);try{localStorage.setItem('pocket-board-view:'+board?.id,next);}catch{}}
  useBoardZoom(canvas,board?.id,zoom,setZoom);
  useEffect(()=>{navigation.current++;setBoard(null);setEditing(null);setForm(null);setBranchAction(null);},[workspaces.selected]);
  async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
  async function open(id:string){const epoch=++navigation.current;await run(async()=>{const next=await request<BoardView>(connection,'/boards/'+id);if(epoch===navigation.current){setBoard(next);setEditing(null);setZoom(1);}});}
  async function save(notes:BoardNote[],versions=board!.versions,optimistic=false){if(!board||lock.current)return;const current=board;if(optimistic)setBoard({...current,notes,versions});await run(async()=>{try{const next=await request<ProjectBoard>(connection,'/boards/'+current.id,{revision:current.revision,notes,versions});setBoard(old=>old?.id===next.id?{...old,...next}:old);setEditing(null);void workspaces.refresh();}catch(error){if(optimistic)setBoard(old=>old?.id===current.id?current:old);throw error;}});}
  const newNote=(point?:{x:number;y:number})=>{if(!board||!canEdit||busy)return;setEditing({id:crypto.randomUUID(),title:'',description:'',branch:point?versions[Math.floor(point.x/340)]||'':'',status:'idea',owner:'',assigneeId:'',priority:'normal',x:point?.x??24,y:point?.y??(70+board.notes.filter(n=>!n.branch).length*300),dependencies:[]});};
  const versions=board?['',...new Set([...board.versions,...board.notes.map(n=>n.branch).filter(Boolean)])]:[];
  const statusLabels={idea:l('Idea','Идея'),questions:l('Questions','Уточнение'),ready:l('Ready','Готово к работе'),working:l('Working','В работе'),review:l('Review','Проверка'),done:l('Done','Готово')};
  function startChat(note:BoardNote){if(!board)return;const deps=note.dependencies.map(id=>board.notes.find(n=>n.id===id)).filter(Boolean);onChat({boardId:board.id,root:board.root,note,prompt:[l('Help develop this project idea. Ask clarifying questions first; identify acceptance criteria and dependencies. Do not implement until we agree on the plan.','Помоги проработать идею проекта. Сначала задай уточняющие вопросы, определи критерии готовности и зависимости. Не приступай к реализации, пока мы не согласуем план.'),note.title,note.description,note.branch?`Git branch: ${note.branch}`:'',deps.length?'Dependencies:\n'+deps.map(n=>n!.title+' ('+n!.status+')').join('\n'):''].filter(Boolean).join('\n\n')});}
  function drag(event:React.PointerEvent<HTMLButtonElement>,note:BoardNote){if(event.button!==0||busy||!canEdit)return;const el=event.currentTarget,card=el.closest('article')!;el.setPointerCapture(event.pointerId);const sx=event.clientX,sy=event.clientY;let x=note.x,y=note.y,moved=false;const move=(e:PointerEvent)=>{if(canvas.current?.dataset.pinching)return;x=Math.max(0,Math.min(19500,note.x+(e.clientX-sx)/zoom));y=Math.max(60,Math.min(19500,note.y+(e.clientY-sy)/zoom));moved=Math.abs(e.clientX-sx)+Math.abs(e.clientY-sy)>4;card.style.left=x+'px';card.style.top=y+'px';};const end=(e:PointerEvent)=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',end);if(e.type==='pointerup'&&moved&&!canvas.current?.dataset.pinching){void save(board!.notes.map(n=>n.id===note.id?{...n,x,y,branch:versions[Math.min(versions.length-1,Math.floor(x/340))]||''}:n),board!.versions,true);}else{card.style.left=note.x+'px';card.style.top=note.y+'px';}};el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);}
  return <section className="work-boards">
    <header className="board-toolbar">{board?<><button className="icon-button" aria-label={l('Back to boards','К доскам')} onClick={()=>{navigation.current++;setBoard(null);}}><ArrowLeft/></button><h2>{board.name}</h2><button className="icon-button" disabled={busy} aria-label={l('Refresh board','Обновить доску')} onClick={()=>void open(board.id)}><RefreshCw size={18}/></button></>:<><h2>{l('Board','Доска')}</h2><ProjectWorkspacePicker value={workspaces}/>{manageWorkspace&&<button onClick={()=>{setPassword('');setEditingWorkspace(false);setTitle('');setFolders([]);setForm('workspace');}}><Plus size={16}/>{l('Workspace','Рабочая область')}</button>}</>}{workspaces.workspace&&<WorkspaceParticipants workspace={workspaces.workspace} connection={connection} manage={manageWorkspace} onChange={workspaces.refresh}/>}</header>
    {(error||workspaces.error)&&<div role="alert" className="board-error">{error||workspaces.error}</div>}
    {!board?<div className="board-index">{workspaces.workspace?<><div className="board-toolbar"><h3>{workspaces.workspace.name}</h3>{host&&<><button onClick={()=>{setTitle('');setRoot(workspaces.workspace!.roots[0]||'');setForm('board');}}><Plus size={16}/>{l('Project board','Доска проекта')}</button>{manageWorkspace&&<button onClick={()=>{setPassword('');setEditingWorkspace(true);setFolders(workspaces.workspace!.roots);setTitle(workspaces.workspace!.name);setForm('workspace');}}>{l('Edit workspace','Изменить область')}</button>}</>}</div><p className="muted">{l('Project boards and chats share this workspace.','Проектные доски и чаты объединены этой рабочей областью.')}</p>{workspaces.catalog.boards.filter(b=>b.workspaceId===workspaces.selected).map(b=><button className="board-index-item" key={b.id} onClick={()=>void open(b.id)}><strong>{b.name}</strong><span>{b.root.split(/[\\/]/).at(-1)} · {b.noteCount} {l('notes','заметок')}</span></button>)}{!workspaces.catalog.boards.some(b=>b.workspaceId===workspaces.selected)&&<p>{l('Create the first board for a project in this workspace.','Создайте первую доску для проекта в этой области.')}</p>}</>:<p>{l('Select a workspace. Create and manage workspaces in the Windows app on the host PC.','\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0440\u0430\u0431\u043e\u0447\u0443\u044e \u043e\u0431\u043b\u0430\u0441\u0442\u044c. \u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0438\u043b\u0438 \u0438\u0437\u043c\u0435\u043d\u0438\u0442\u044c \u0435\u0451 \u043c\u043e\u0436\u043d\u043e \u0432 Windows-\u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0438 \u043d\u0430 \u041f\u041a \u0445\u043e\u0441\u0442\u0430.')}</p>}</div>:<>
      <div className="board-tools"><div className="board-view-switch" role="group" aria-label={l('Board view','\u0412\u0438\u0434 \u0434\u043e\u0441\u043a\u0438')}><button aria-pressed={view==='board'} onClick={()=>changeView('board')}>{l('Board','\u0414\u043e\u0441\u043a\u0430')}</button><button aria-pressed={view==='people'} onClick={()=>changeView('people')}>{l('People','\u041b\u044e\u0434\u0438')}</button></div><span role="status">{busy?l('Saving…','Сохранение…'):l('Saved on PC','Сохранено на ПК')}</span></div>
      {view==='board'&&board.error&&<p className="board-git-warning">{board.error}</p>}
      <div className="board-viewport" hidden={view!=='board'} ref={canvas}><div className="board-scaled-area" style={{width:Math.max(1100,(versions.length+1)*340,...board.notes.map(n=>n.x+330))*zoom,height:Math.max(800,...board.notes.map(n=>n.y+330))*zoom}}><div className="board-canvas" style={{width:Math.max(1100,versions.length*340,...board.notes.map(n=>n.x+330)),height:Math.max(800,...board.notes.map(n=>n.y+330)),transform:`scale(${zoom})`}}>
        {versions.map((v,i)=>v?<BoardBranchHeading key={v} name={v} left={i*340} disabled={busy||!host} onRename={()=>{setError('');setBranchAction({previous:v,name:v});}}/>:<div className="board-version" key={v} style={{left:i*340}}><strong>{l('Ideas','\u0418\u0434\u0435\u0438')}</strong></div>)}
        {host&&<button className="board-add-branch" style={{left:versions.length*340}} aria-label={l('Create branch','\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0432\u0435\u0442\u043a\u0443')} disabled={busy} onClick={()=>{setError('');setBranchAction({name:''});}}><Plus size={24}/></button>}
        <svg className="board-edges" aria-label={l('Dependencies','Зависимости')}>{board.notes.flatMap(n=>n.dependencies.map(id=>{const dep=board.notes.find(v=>v.id===id);return dep?<g key={n.id+id}><path d={`M ${dep.x+280} ${dep.y+80} C ${dep.x+340} ${dep.y+80},${n.x-60} ${n.y+80},${n.x} ${n.y+80}`}/><circle cx={n.x} cy={n.y+80} r="4"/></g>:null;}))}</svg>
        {board.notes.map(n=><article className={'board-note status-'+n.status} key={n.id} style={{left:n.x,top:n.y}}><button className="note-drag" aria-label={l('Move note','Переместить заметку')+' '+n.title} onPointerDown={e=>drag(e,n)} onKeyDown={e=>{const dir:Record<string,[number,number]>={ArrowLeft:[-24,0],ArrowRight:[24,0],ArrowUp:[0,-24],ArrowDown:[0,24]};if(canEdit&&dir[e.key]){e.preventDefault();const [x,y]=dir[e.key];void save(board.notes.map(v=>v.id===n.id?{...v,x:Math.max(0,v.x+x),y:Math.max(60,v.y+y),branch:versions[Math.min(versions.length-1,Math.floor(Math.max(0,v.x+x)/340))]||''}:v));}}}>⠿ </button><button className="note-content" onClick={()=>setEditing({...n,dependencies:[...n.dependencies]})}><strong>{n.title}</strong><p>{n.description||l('Add details…','Добавить описание…')}</p><BoardTaskMeta note={n} people={people} status={statusLabels[n.status]}/></button><button className="note-chat" disabled={!host&&!n.chat} onClick={()=>startChat(n)}><MessageSquare size={15}/>{n.chat?l('Open chat','Открыть чат'):l('Discuss with AI','Обсудить с AI')}</button></article>)}
      </div></div></div>{view==='people'&&<BoardPeople notes={board.notes} people={people} statusLabels={statusLabels} onOpen={n=>setEditing({...n,dependencies:[...n.dependencies]})}/>}</>}
    <BoardContextMenu viewport={canvas} boardId={board?.id} zoom={zoom} enabled={view==='board'&&!!board&&canEdit&&!busy&&!editing&&!form&&!branchAction} onCreate={newNote}/>
    {branchAction&&board&&<div className="modal-backdrop"><form className="board-dialog" role="dialog" aria-modal="true" aria-label={branchAction.previous?l('Rename branch','\u041f\u0435\u0440\u0435\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u0442\u044c \u0432\u0435\u0442\u043a\u0443'):l('Create branch','\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0432\u0435\u0442\u043a\u0443')} onSubmit={e=>{e.preventDefault();void run(async()=>{const next=await request<BoardView>(connection,'/boards/'+board.id+'/branch',{...branchAction,revision:board.revision});setBoard(next);setBranchAction(null);void workspaces.refresh();});}}><h2>{branchAction.previous?l('Rename this branch?','\u041f\u0435\u0440\u0435\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u0442\u044c \u0432\u0435\u0442\u043a\u0443?'):l('Create a branch?','\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0432\u0435\u0442\u043a\u0443?')}</h2><label>{l('Branch name','\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432\u0435\u0442\u043a\u0438')}<input autoFocus required maxLength={200} value={branchAction.name} onChange={e=>setBranchAction({...branchAction,name:e.target.value})}/></label><p role="alert">{error}</p><footer><button type="button" disabled={busy} onClick={()=>setBranchAction(null)}>{l('Cancel','\u041e\u0442\u043c\u0435\u043d\u0430')}</button><button className="primary" disabled={busy||!branchAction.name.trim()}>{branchAction.previous?l('Rename','\u041f\u0435\u0440\u0435\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u0442\u044c'):l('Create','\u0421\u043e\u0437\u0434\u0430\u0442\u044c')}</button></footer></form></div>}
    {form&&<div className="modal-backdrop"><form className="board-dialog" role="dialog" aria-modal="true" aria-label={form==='workspace'?l('Workspace settings','Рабочая область'):l('New board','Новая доска')} onSubmit={e=>{e.preventDefault();void run(async()=>{if(form==='workspace'){if(!manageWorkspace)throw Error('Create and manage workspaces on the host PC.');const result=await request<{id:string}>(connection,'/workspaces',{...(editingWorkspace?{id:workspaces.workspace!.id}:{}),name:title,roots:folders,...(password?{password}:{})});workspaces.select(result.id);}else{const result=await request<ProjectBoard>(connection,'/boards',{workspaceId:workspaces.selected,name:title,root});setBoard(await request<BoardView>(connection,'/boards/'+result.id));}await workspaces.refresh();setForm(null);});}}><h2>{form==='workspace'?l('Workspace','Рабочая область'):l('Project board','Доска проекта')}</h2><label>{l('Name','Название')}<input autoFocus required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label>{form==='workspace'?<><label>{l('Workspace password (10+ characters)','\u041f\u0430\u0440\u043e\u043b\u044c \u043e\u0431\u043b\u0430\u0441\u0442\u0438 (10+)')}<input type="password" autoComplete="new-password" required={!editingWorkspace} minLength={10} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label><fieldset><legend>{l('Repository','\u0420\u0435\u043f\u043e\u0437\u0438\u0442\u043e\u0440\u0438\u0439')}</legend>{roots.map(p=><label className="board-check" key={p}><input type="radio" name="workspace-repository" checked={folders.length===1&&folders[0]===p} onChange={()=>setFolders([p])}/><span>{p.split(/[\\/]/).at(-1)}<small>{p}</small></span></label>)}</fieldset></>:<label>{l('Project','Проект')}<select value={root} onChange={e=>setRoot(e.target.value)}>{workspaces.workspace?.roots.map(p=><option key={p} value={p}>{p.split(/[\\/]/).at(-1)}</option>)}</select></label>}<p role="alert">{error}</p><footer><button type="button" onClick={()=>setForm(null)}>{l('Cancel','Отмена')}</button><button className="primary" disabled={busy||!title.trim()||form==='workspace'&&folders.length!==1}>{l('Save','Сохранить')}</button></footer></form></div>}
    {editing&&board&&<div className="modal-backdrop"><form className="board-dialog" role="dialog" aria-modal="true" aria-label={l('Note details','Параметры заметки')} onSubmit={e=>{e.preventDefault();void save([...board.notes.filter(n=>n.id!==editing.id),editing]);}}><h2>{l('Note','Заметка')}</h2><label>{l('Title','Название')}<input autoFocus required maxLength={160} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>{l('Description / acceptance criteria','Описание / критерии готовности')}<textarea maxLength={20000} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>{l('Status','Статус')}<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as BoardNote['status']})}>{Object.entries(statusLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>{l('Priority','\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442')}<select value={editing.priority||'normal'} onChange={e=>setEditing({...editing,priority:e.target.value as BoardNote['priority']})}>{Object.entries(priorityLabels).map(([value,text])=><option key={value} value={value}>{text[ru?1:0]}</option>)}</select></label><label>{l('Assignee','\u0418\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c')}<select value={editing.assigneeId||(editing.owner?'legacy:'+editing.owner:'')} onChange={e=>{const person=people.find(p=>p.id===e.target.value);setEditing({...editing,assigneeId:person?.id.startsWith('legacy:')?'':person?.id||'',owner:person?.name||''});}}><option value="">{l('Unassigned','\u041d\u0435 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u043e')}</option>{people.map(p=><option key={p.id} value={p.id}>{p.id==='host'?l('Host','\u0425\u043e\u0441\u0442'):p.name}</option>)}</select></label><p role="alert">{error}</p><footer><button type="button" onClick={()=>setEditing(null)}>{l('Cancel','Отмена')}</button><button className="primary" disabled={busy||!canEdit||!editing.title.trim()}>{l('Save','Сохранить')}</button></footer></form></div>}
  </section>;
}
