import {BoardRepository} from './BoardRepository';
import {DeleteWorkspaceItem} from './DeleteWorkspaceItem';
import {boardPlacement} from './board-placement';
import {useBoardPan} from './use-board-pan';
import {NoteAssignees,withAssignees} from './NoteAssignees';
import {BoardPeople,BoardTaskMeta,boardPeople,priorityLabels} from './BoardPeople';
import {BoardBranchHeading} from './BoardBranchHeading';
import {BoardContextMenu} from './BoardContextMenu';
import {useBoardZoom} from './use-board-zoom';
import {WorkspaceParticipants} from './WorkspaceParticipants';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,Plus,RefreshCw,MessageSquare,X} from 'lucide-react';
import {request,type Connection} from './api';
import {useLanguage} from './i18n';
import {type useProjectWorkspaces} from './project-workspaces';
import type {ProjectBoard,BoardNote} from '../server/boards';
import './work-boards.css';
export type BoardChat={root:string;prompt:string;note:BoardNote;boardId:string;connectionUrl?:string};
type BoardView=ProjectBoard&{branches:string[];error?:string};
export function WorkBoards({connection,roots,workspaces,onChat,local=false,compactContext=false}:{connection:Connection;roots:string[];workspaces:ReturnType<typeof useProjectWorkspaces>;onChat(chat:BoardChat):void;local?:boolean;compactContext?:boolean}){
  const ru=useLanguage()==='ru',l=(en:string,ruText:string)=>ru?ruText:en;
  const [board,setBoard]=useState<BoardView|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<BoardNote|null>(null),[form,setForm]=useState<'board'|null>(null),[title,setTitle]=useState(''),[folders,setFolders]=useState<string[]>([]),[root,setRoot]=useState(''),[zoom,setZoom]=useState(1);
  const [view,setView]=useState<'board'|'people'>('board');
  const [branchAction,setBranchAction]=useState<{previous?:string;name:string}|null>(null);
  const host=workspaces.catalog.host;const manageWorkspace=false;const canEdit=!board?.source&&!workspaces.offline&&(host||!!workspaces.workspace&&workspaces.workspace.role!=='viewer');
  const lock=useRef(false),navigation=useRef(0),canvas=useRef<HTMLDivElement>(null);
  useEffect(()=>{try{setView(localStorage.getItem('pocket-board-view:'+board?.id)==='people'?'people':'board');}catch{setView('board');}},[board?.id]);
  const people=boardPeople(workspaces.workspace,board?.notes||[]);
  function changeView(next:'board'|'people'){setView(next);try{localStorage.setItem('pocket-board-view:'+board?.id,next);}catch{}}
  useBoardZoom(canvas,board?.id,zoom,setZoom);useBoardPan(canvas,board?.id);
  useEffect(()=>{navigation.current++;setBoard(null);setEditing(null);setForm(null);setBranchAction(null);},[workspaces.selected,local]);
  async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await action();}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}}
  async function open(id:string){const epoch=++navigation.current;await run(async()=>{const next=await request<BoardView>(connection,'/boards/'+id);if(epoch===navigation.current){setBoard(next);setEditing(null);setZoom(1);}});}
  async function save(notes:BoardNote[],versions=board!.versions,optimistic=false){if(!board||lock.current)return;const current=board;if(optimistic)setBoard({...current,notes,versions});await run(async()=>{try{const next=await request<ProjectBoard>(connection,'/boards/'+current.id,{revision:current.revision,notes,versions});setBoard(old=>old?.id===next.id?{...old,...next}:old);setEditing(null);void workspaces.refresh();}catch(error){if(optimistic)setBoard(old=>old?.id===current.id?current:old);throw error;}});}
  const newNote=(point?:{x:number;y:number})=>{if(!board||!canEdit||busy)return;setEditing({id:crypto.randomUUID(),title:'',description:'',branch:point?versions[Math.floor(point.x/340)]||'':'',status:'idea',owner:'',assigneeId:'',assigneeIds:[],priority:'normal',x:point?.x??24,y:point?.y??(70+board.notes.filter(n=>!n.branch).length*300),dependencies:[]});};
  const versions=board?['',...new Set([...board.versions,...board.notes.map(n=>n.branch).filter(Boolean)])]:[];
  const statusLabels={idea:l('Idea','Идея'),questions:l('Questions','Уточнение'),ready:l('Ready','Готово к работе'),working:l('Working','В работе'),review:l('Review','Проверка'),done:l('Done','Готово')};
  function startChat(note:BoardNote){if(!board)return;const deps=note.dependencies.map(id=>board.notes.find(n=>n.id===id)).filter(Boolean);onChat({connectionUrl:connection.url,boardId:board.id,root:board.root,note,prompt:[l('Help develop this project idea. Ask clarifying questions first; identify acceptance criteria and dependencies. Do not implement until we agree on the plan.','Помоги проработать идею проекта. Сначала задай уточняющие вопросы, определи критерии готовности и зависимости. Не приступай к реализации, пока мы не согласуем план.'),note.title,note.description,note.branch?`Git branch: ${note.branch}`:'',deps.length?'Dependencies:\n'+deps.map(n=>n!.title+' ('+n!.status+')').join('\n'):''].filter(Boolean).join('\n\n')});}
  function drag(event:React.PointerEvent<HTMLButtonElement>,note:BoardNote){
    if(event.button!==0||busy||!canEdit)return;const el=event.currentTarget,card=el.closest('article')!;el.setPointerCapture(event.pointerId);const sx=event.clientX,sy=event.clientY;let placement=boardPlacement(note.x,note.y,versions,card.offsetWidth),moved=false;
    const highlight=(column:number|null)=>{canvas.current?.querySelectorAll<HTMLElement>('.board-drop-zone').forEach(zone=>zone.classList.toggle('board-drop-active',Number(zone.dataset.column)===column));card.classList.toggle('board-note-dragging',column!==null);};
    const move=(e:PointerEvent)=>{if(canvas.current?.dataset.pinching)return;placement=boardPlacement(note.x+(e.clientX-sx)/zoom,note.y+(e.clientY-sy)/zoom,versions,card.offsetWidth);moved=Math.abs(e.clientX-sx)+Math.abs(e.clientY-sy)>4;if(moved){highlight(placement.column);card.style.left=placement.x+'px';card.style.top=placement.y+'px';}};
    const end=(e:PointerEvent)=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',end);highlight(null);if(e.type==='pointerup'&&moved&&!canvas.current?.dataset.pinching){const {column,...position}=placement;void save(board!.notes.map(n=>n.id===note.id?{...n,...position}:n),board!.versions,true);}else{card.style.left=note.x+'px';card.style.top=note.y+'px';}};
    el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);
  }
  if(workspaces.workspace?.me?.approval&&workspaces.workspace.me.approval!=='approved')return <section className="workspace-waiting" role="status"><h2>{workspaces.workspace.me.approval==='rejected'?l('Request declined','Заявка отклонена'):l('Waiting for host approval','Ожидание подтверждения хоста')}</h2><p>{workspaces.workspace.me.approval==='rejected'?l('Contact the host to discuss access.','Свяжитесь с хостом, чтобы обсудить доступ.'):l('Your request has been sent. The board will open automatically after approval on the PC.','Заявка отправлена. Доска откроется автоматически после подтверждения на ПК.')}</p><button onClick={()=>void workspaces.refresh()}>{l('Check status','Проверить статус')}</button></section>;
  return <section className="work-boards" aria-busy={busy}>
    <header className="board-header" hidden={compactContext&&!board}>
      {!compactContext&&<div className="board-header-context"><h1>{(local?l('Local boards','Локальные доски'):workspaces.workspace?.name)||l('Board','\u0414\u043e\u0441\u043a\u0430')}</h1>{!local&&workspaces.workspace&&<WorkspaceParticipants workspace={workspaces.workspace} connection={connection} manage={manageWorkspace} onChange={workspaces.refresh}/>}</div>}
      {board?<div className="board-header-navigation"><button className="icon-button" aria-label={l('Back to boards','\u041a \u0434\u043e\u0441\u043a\u0430\u043c')} onClick={()=>{navigation.current++;setBoard(null);}}><ArrowLeft/></button><h2 title={board.name}>{board.name}</h2>{connection.desktop&&workspaces.catalog.canManageWorkspaces&&<BoardRepository connection={connection} boardId={board.id} roots={[board.root]} onImported={workspaces.refresh}/>}{connection.desktop&&workspaces.catalog.canManageWorkspaces&&<DeleteWorkspaceItem connection={connection} kind="boards" id={board.id} name={board.name} onDeleted={async()=>{navigation.current++;setBoard(null);await workspaces.refresh();}}/>}{board.source&&<small className="board-source">{l('Project roadmap · refresh to update','Доска проекта · обновляется по кнопке')}</small>}{!board.source&&board.versionSource==='planned'&&<small className="board-planned-label">{l('Planned · Git not linked','План · Git не привязан')}</small>}<div className="board-view-switch" role="group" aria-label={l('Board view','\u0412\u0438\u0434 \u0434\u043e\u0441\u043a\u0438')}><button aria-pressed={view==='board'} onClick={()=>changeView('board')}>{l('Board','\u0414\u043e\u0441\u043a\u0430')}</button><button aria-pressed={view==='people'} onClick={()=>changeView('people')}>{l('People','\u041b\u044e\u0434\u0438')}</button></div><button className="icon-button" disabled={busy} aria-label={l('Refresh board','\u041e\u0431\u043d\u043e\u0432\u0438\u0442\u044c \u0434\u043e\u0441\u043a\u0443')} onClick={()=>void open(board.id)}><RefreshCw size={18}/></button></div>:null}
    </header>
    {(error||workspaces.error)&&<div role="alert" className="board-error">{error||workspaces.error}</div>}
    {!board?<div className="board-index">{(local||workspaces.workspace)?<><div className="board-toolbar">{connection.desktop&&workspaces.catalog.canManageWorkspaces&&<BoardRepository connection={connection} roots={local?roots:workspaces.workspace?.roots||[]} workspaceId={local?undefined:workspaces.selected} onImported={workspaces.refresh}/>}{host&&!workspaces.offline&&<><button className="board-create-button primary" onClick={()=>{setTitle('');setRoot((local?roots:workspaces.workspace!.roots)[0]||'');setForm('board');}}><Plus size={16}/>{l('Create board','Создать доску')}</button></>}</div>{workspaces.catalog.boards.filter(b=>local?!b.workspaceId:b.workspaceId===workspaces.selected).map(b=><button className="board-index-item" key={b.id} onClick={()=>void open(b.id)}><strong>{b.name}</strong><span>{b.root.split(/[\\/]/).at(-1)} · {b.noteCount} {l('notes','заметок')}</span></button>)}{!workspaces.catalog.boards.some(b=>local?!b.workspaceId:b.workspaceId===workspaces.selected)&&<p>{host?l('Create the first board for a project in this workspace.','Создайте первую доску для проекта в этой области.'):l('No boards yet. The host can create one on the PC.','Досок пока нет. Хост может создать доску на ПК.')}</p>}</>:<p>{l('Scan the workspace QR on the host PC to join its board.','\u041e\u0442\u0441\u043a\u0430\u043d\u0438\u0440\u0443\u0439\u0442\u0435 QR \u0440\u0430\u0431\u043e\u0447\u0435\u0439 \u043e\u0431\u043b\u0430\u0441\u0442\u0438 \u043d\u0430 \u041f\u041a \u0445\u043e\u0441\u0442\u0430.')}</p>}</div>:<>

      {view==='board'&&board.error&&<p className="board-git-warning">{board.error}</p>}
      <div className="board-viewport" hidden={view!=='board'} ref={canvas}><div className="board-scaled-area" style={{width:Math.max(1100,(versions.length+1)*340,...board.notes.map(n=>n.x+330))*zoom,height:Math.max(800,...board.notes.map(n=>n.y+330))*zoom}}><div className="board-canvas" style={{width:Math.max(1100,versions.length*340,...board.notes.map(n=>n.x+330)),height:Math.max(800,...board.notes.map(n=>n.y+330)),transform:`scale(${zoom})`}}>
        {versions.map((branch,column)=><div key={'drop:'+branch} className="board-drop-zone" data-column={column} style={{left:column*340,width:340,height:'100%'}}/>)}<svg className="board-roadmap-links" aria-label={l('Version sequence','Последовательность версий')} width={versions.length*340} height="68"><defs><marker id="roadmap-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z"/></marker></defs>{versions.slice(1,-1).map((v,i)=><path key={v} d={'M '+((i+1)*340+160)+' 62 L '+((i+2)*340+150)+' 62'} markerEnd="url(#roadmap-arrow)"/>)}</svg>{versions.map((v,i)=>v?<BoardBranchHeading key={v} name={v} left={i*340} disabled={busy||!host||workspaces.offline||!!board.source} onRename={()=>{setError('');setBranchAction({previous:v,name:v});}}/>:<div className="board-version" key={v} style={{left:i*340}}><strong>{l('Ideas','\u0418\u0434\u0435\u0438')}</strong></div>)}
        {host&&!board.source&&<button className="board-add-branch" style={{left:versions.length*340}} aria-label={l(board.versionSource==='planned'?'Create version':'Create branch',board.versionSource==='planned'?'Создать версию':'\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0432\u0435\u0442\u043a\u0443')} disabled={busy||workspaces.offline} onClick={()=>{setError('');setBranchAction({name:''});}}><Plus size={24}/></button>}
        <svg className="board-edges" aria-label={l('Dependencies','Зависимости')}>{board.notes.flatMap(n=>n.dependencies.map(id=>{const dep=board.notes.find(v=>v.id===id);return dep?<g key={n.id+id}><path d={`M ${dep.x+280} ${dep.y+80} C ${dep.x+340} ${dep.y+80},${n.x-60} ${n.y+80},${n.x} ${n.y+80}`}/><circle cx={n.x} cy={n.y+80} r="4"/></g>:null;}))}</svg>
        {board.notes.map(n=><article className={'board-note status-'+n.status} key={n.id} style={{left:n.x,top:n.y}}><button className="note-drag" aria-label={l('Move note','Переместить заметку')+' '+n.title} onPointerDown={e=>drag(e,n)} onKeyDown={e=>{const dir:Record<string,[number,number]>={ArrowLeft:[-24,0],ArrowRight:[24,0],ArrowUp:[0,-24],ArrowDown:[0,24]};if(canEdit&&dir[e.key]){e.preventDefault();const [x,y]=dir[e.key];void save(board.notes.map(v=>v.id===n.id?{...v,...boardPlacement(v.x+(x?Math.sign(x)*340:0),v.y+y,versions)}:v));}}}>⠿ </button><button className="note-content" onClick={()=>setEditing({...n,dependencies:[...n.dependencies]})}><strong>{n.title}</strong><p>{n.description||l('Add details…','Добавить описание…')}</p><BoardTaskMeta note={n} people={people} status={statusLabels[n.status]}/></button>{!board.source&&<button className="note-chat" disabled={!host&&!n.chat} onClick={()=>startChat(n)}><MessageSquare size={15}/>{n.chat?l('Open chat','Открыть чат'):l('Discuss with AI','Обсудить с AI')}</button>}<NoteAssignees note={n} people={people} disabled={busy} onChange={canEdit?ids=>void save(board.notes.map(v=>v.id===n.id?withAssignees(v,ids,people):v)):undefined}/></article>)}
      </div></div></div>{view==='people'&&<BoardPeople disabled={busy} onAssign={canEdit?(note,ids)=>void save(board.notes.map(v=>v.id===note.id?withAssignees(v,ids,people):v)):undefined} notes={board.notes} people={people} statusLabels={statusLabels} onOpen={n=>setEditing({...n,dependencies:[...n.dependencies]})}/>}</>}
    
        <BoardContextMenu viewport={canvas} boardId={board?.id} zoom={zoom} enabled={view==='board'&&!!board&&canEdit&&!busy&&!editing&&!form&&!branchAction} onCreate={newNote}/>
    {branchAction&&board&&<div className="modal-backdrop"><form className="board-dialog" role="dialog" aria-modal="true" aria-label={branchAction.previous?l(board.versionSource==='planned'?'Rename version':'Rename branch',board.versionSource==='planned'?'Переименовать версию':'\u041f\u0435\u0440\u0435\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u0442\u044c \u0432\u0435\u0442\u043a\u0443'):l(board.versionSource==='planned'?'Create version':'Create branch',board.versionSource==='planned'?'Создать версию':'Создать ветку')} onSubmit={e=>{e.preventDefault();void run(async()=>{const next=await request<BoardView>(connection,'/boards/'+board.id+'/branch',{...branchAction,revision:board.revision});setBoard(next);setBranchAction(null);void workspaces.refresh();});}}><h2>{branchAction.previous?l(board.versionSource==='planned'?'Rename this version?':'Rename this branch?',board.versionSource==='planned'?'Переименовать эту версию?':'\u041f\u0435\u0440\u0435\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u0442\u044c \u0432\u0435\u0442\u043a\u0443?'):l(board.versionSource==='planned'?'Create a planned version?':'Create a branch?',board.versionSource==='planned'?'Создать плановую версию?':'\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u0432\u0435\u0442\u043a\u0443?')}</h2><label>{l(board.versionSource==='planned'?'Version name':'Branch name',board.versionSource==='planned'?'Название версии':'\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0432\u0435\u0442\u043a\u0438')}<input autoFocus required maxLength={200} value={branchAction.name} onChange={e=>setBranchAction({...branchAction,name:e.target.value})}/></label><p role="alert">{error}</p><footer><button type="button" disabled={busy} onClick={()=>setBranchAction(null)}>{l('Cancel','\u041e\u0442\u043c\u0435\u043d\u0430')}</button><button className="primary" disabled={busy||!branchAction.name.trim()}>{branchAction.previous?l('Rename','\u041f\u0435\u0440\u0435\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u0442\u044c'):l('Create','\u0421\u043e\u0437\u0434\u0430\u0442\u044c')}</button></footer></form></div>}
    {form&&<div className="modal-backdrop"><form className="board-dialog" role="dialog" aria-modal="true" aria-label={l('Create board','Создать доску')} onSubmit={e=>{e.preventDefault();void run(async()=>{const result=await request<ProjectBoard>(connection,'/boards',{...(local?{}:{workspaceId:workspaces.selected}),name:title,root,language:ru?'ru':'en'});setBoard(await request<BoardView>(connection,'/boards/'+result.id));await workspaces.refresh();setForm(null);});}}><h2>{l('Project board','Доска проекта')}</h2><label>{l('Name','Название')}<input autoFocus required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label>{local?<label>{l('Repository','Репозиторий')}<select aria-label={l('Board repository','Репозиторий доски')} required value={root} onChange={e=>setRoot(e.target.value)}>{roots.map(r=><option key={r} value={r}>{r.split(/[\\/]/).at(-1)}</option>)}</select></label>:<p>{workspaces.workspace?.roots[0]?.split(/[\\/]/).at(-1)}</p>}<p role="alert">{error}</p><footer><button type="button" onClick={()=>setForm(null)}>{l('Cancel','Отмена')}</button><button className="primary" disabled={busy||!title.trim()}>{l('Create','Создать')}</button></footer></form></div>}
    {editing&&board&&<div className="modal-backdrop"><form className="board-dialog" role="dialog" aria-modal="true" aria-label={l('Note details','Параметры заметки')} onSubmit={e=>{e.preventDefault();void save([...board.notes.filter(n=>n.id!==editing.id),editing]);}}><h2>{l('Note','Заметка')}</h2><label>{l('Title','Название')}<input autoFocus readOnly={!canEdit} required maxLength={160} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>{l('Description / acceptance criteria','Описание / критерии готовности')}<textarea readOnly={!canEdit} maxLength={20000} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>{l('Status','Статус')}<select disabled={!canEdit} value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as BoardNote['status']})}>{Object.entries(statusLabels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>{l('Priority','\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442')}<select disabled={!canEdit} value={editing.priority||'normal'} onChange={e=>setEditing({...editing,priority:e.target.value as BoardNote['priority']})}>{Object.entries(priorityLabels).map(([value,text])=><option key={value} value={value}>{text[ru?1:0]}</option>)}</select></label><NoteAssignees note={editing} people={people} disabled={busy} onChange={canEdit?ids=>setEditing(withAssignees(editing,ids,people)):undefined}/><p role="alert">{error}</p><footer><button type="button" onClick={()=>setEditing(null)}>{l('Cancel','Отмена')}</button><button className="primary" disabled={busy||!canEdit||!editing.title.trim()}>{l('Save','Сохранить')}</button></footer></form></div>}
  </section>;
}
